import type { Dream } from '@/types/dream'

const STORAGE_KEY = 'dreamscope_dreams'

export function seedDemoData() {
  const existing = localStorage.getItem(STORAGE_KEY)
  if (existing) return

  const dreams: Dream[] = [
    {
      id: crypto.randomUUID(),
      text: '在一片无边的大海中漂浮，海水温暖而透明。看到水下有发光的鱼群游过，远处有一座古老的灯塔。突然巨浪袭来，我抓住了一块漂浮的木板。',
      date: '2026-05-01',
      wakeTime: '06:30',
      emotionScore: 4,
      clarityScore: 4,
      people: ['小明'],
      places: ['大海', '灯塔'],
      keywords: ['水', '漂浮', '恐惧', '鱼'],
      createdAt: '2026-05-01T06:30:00Z',
    },
    {
      id: crypto.randomUUID(),
      text: '站在学校的走廊里，找不到教室。走廊越来越长，两边的门都打不开。突然听到上课铃声，开始奔跑。',
      date: '2026-05-05',
      wakeTime: '07:15',
      emotionScore: 2,
      clarityScore: 3,
      people: [],
      places: ['学校'],
      keywords: ['迷失', '奔跑', '焦虑'],
      createdAt: '2026-05-05T07:15:00Z',
    },
    {
      id: crypto.randomUUID(),
      text: '和妈妈一起在老家的院子里摘果子，阳光很温暖。院子里那棵大树还在，上面结满了金色的果实。妈妈笑着递给我一个。',
      date: '2026-05-10',
      wakeTime: '08:00',
      emotionScore: 5,
      clarityScore: 5,
      people: ['妈妈'],
      places: ['老家', '院子'],
      keywords: ['温暖', '果实', '阳光', '回忆'],
      createdAt: '2026-05-10T08:00:00Z',
    },
    {
      id: crypto.randomUUID(),
      text: '在一个巨大的图书馆里，书架一直延伸到看不见的尽头。每本书都闪烁着微弱的光。我翻开一本，里面的文字开始漂浮起来。',
      date: '2026-05-15',
      wakeTime: '06:45',
      emotionScore: 4,
      clarityScore: 4,
      people: [],
      places: ['图书馆'],
      keywords: ['书', '漂浮', '光', '神秘'],
      createdAt: '2026-05-15T06:45:00Z',
    },
    {
      id: crypto.randomUUID(),
      text: '走在一条陌生的街道上，路边的房子都是倒着的。天空是紫色的，有两轮月亮。小明在前面等我，但我怎么也走不到他身边。',
      date: '2026-05-18',
      wakeTime: '05:30',
      emotionScore: 2,
      clarityScore: 5,
      people: ['小明'],
      places: ['街道'],
      keywords: ['迷失', '奔跑', '月光', '恐惧'],
      createdAt: '2026-05-18T05:30:00Z',
    },
    {
      id: crypto.randomUUID(),
      text: '在山顶的寺庙里打坐，周围一片寂静。突然听到远处的钟声，身体变得很轻，像要飞起来一样。山下的云海翻涌，非常壮观。',
      date: '2026-05-22',
      wakeTime: '07:00',
      emotionScore: 5,
      clarityScore: 3,
      people: [],
      places: ['山顶', '寺庙'],
      keywords: ['宁静', '飞翔', '云', '光'],
      createdAt: '2026-05-22T07:00:00Z',
    },
    {
      id: crypto.randomUUID(),
      text: '回到小时候的家，但是房子变大了好多倍。桌子像山一样高，杯子像游泳池一样大。我变成了很小的人，在巨大的家具之间穿行。',
      date: '2026-05-25',
      wakeTime: '06:20',
      emotionScore: 3,
      clarityScore: 4,
      people: [],
      places: ['家'],
      keywords: ['变大', '回忆', '神秘'],
      createdAt: '2026-05-25T06:20:00Z',
    },
    {
      id: crypto.randomUUID(),
      text: '在深水中游泳，水越来越深越来越暗。突然看到下方有一束光，游过去发现是一座水下城市的废墟。废墟里有发光的鱼在游动。',
      date: '2026-05-28',
      wakeTime: '05:50',
      emotionScore: 3,
      clarityScore: 5,
      people: [],
      places: ['深海', '废墟'],
      keywords: ['水', '鱼', '光', '恐惧', '神秘'],
      createdAt: '2026-05-28T05:50:00Z',
    },
    {
      id: crypto.randomUUID(),
      text: '在一场暴风雨中开车，路完全看不见了。车灯照出前方有一座桥，桥的另一端消失在黑暗中。我犹豫着要不要开过去。',
      date: '2026-05-30',
      wakeTime: '04:30',
      emotionScore: 1,
      clarityScore: 4,
      people: [],
      places: ['桥', '公路'],
      keywords: ['暴风雨', '恐惧', '选择'],
      createdAt: '2026-05-30T04:30:00Z',
    },
    {
      id: crypto.randomUUID(),
      text: '和朋友们在一个花园里野餐，到处都是花。小明带来了一篮水果，阳光温暖。突然所有的花开始旋转，变成了一幅画。',
      date: '2026-06-01',
      wakeTime: '07:30',
      emotionScore: 4,
      clarityScore: 3,
      people: ['小明', '小红'],
      places: ['花园'],
      keywords: ['果实', '阳光', '花', '温暖'],
      createdAt: '2026-06-01T07:30:00Z',
    },
  ]

  localStorage.setItem(STORAGE_KEY, JSON.stringify(dreams))
  window.location.reload()
}
